import type { Command } from 'commander';
import { z } from 'zod';
import { rawBreakdownSchema, rawOperationSchema } from '../api/schemas.js';
import { configPath } from '../auth/config.js';
import { DougsError, ExitCode, toDougsError } from '../output/errors.js';
import { style } from '../output/style.js';
import { VERSION } from '../version.js';
import { contextOf } from './context.js';
import { withExamples } from './shared.js';

/**
 * Field names observed on operations / breakdowns when this version shipped.
 * New names are reported as "unknown" (Dougs added something), which is an
 * early warning, not an error.
 */
const KNOWN_OPERATION_FIELDS = new Set(
  `messengerId id companyId transactionId investmentId reversedOperationId reverseOperationId deleted detachDeleted
   isDraft autogenerated type wording memo amount isInbound date validatedAt validated excluded exclusionReason
   manuallyLocked needsAttention message metadata accountingSurveyId flag creatorId reversalDate salesChannelId
   createdAt updatedAt creator messenger breakdowns transaction isBank isCustomerCreditNote isSupplierCreditNote
   isExpense isInvoice isClientInvoice isVendorInvoice isInvoiceSupplier isInvoiceCustomer isKilometricIndemnity
   isCashPayment isCashExpense isMiscellaneous isCustomerEditableMiscellaneous isAccountingSurveyMiscellaneous
   isDispatch isReconciliation isCashRegisterDispatch isCashRegisterFee dispatchType name allowAddingBreakdown
   lockedByDate hasVat vatRate vatAmount totalAmount sections description errors allowUnbalanced isTotalAmountValid
   sourceDocumentAttachments sourceDocumentCandidate`.split(/\s+/),
);
const KNOWN_BREAKDOWN_FIELDS = new Set(
  `unitAmount uuid associationData date id companyId operationId amount quantity wording isInbound isFee
   isCounterpart section manualVatAmount categoryId predictedCategoryId resolvedCategoryId resolvedCategoryPath
   autocategorizationMethod isManuallyCategorized metadata creatorId createdAt updatedAt hasVat isRefund
   vatAmountWithRecoverageRate vatAmount isVatAmountManuallyModified vatRate isNonTaxable isVatReversable
   isVatAmountEditable isAmountEditable isCategoryEditable isDeletable categoryWording
   amountExcludingTaxesWithRecoverageRate categoryGroup associations hasAssociatedAccrualInvoice`.split(
    /\s+/,
  ),
);

/** Fields the CLI cannot work without (optional ones may legitimately be absent). */
function requiredKeys(shape: Record<string, z.ZodType>): string[] {
  return Object.entries(shape)
    .filter(([, field]) => !field.safeParse(undefined).success)
    .map(([key]) => key);
}
const REQUIRED_OPERATION_FIELDS = requiredKeys(rawOperationSchema.shape);
const REQUIRED_BREAKDOWN_FIELDS = requiredKeys(rawBreakdownSchema.shape);

interface Check {
  name: string;
  ok: boolean;
  detail: string;
}

export function schemaDrift(samples: unknown[]) {
  const issues: { sample: number; path: string; message: string }[] = [];
  const unknownFields = new Set<string>();
  const missingFields = new Set<string>();
  samples.forEach((sample, i) => {
    const parsed = rawOperationSchema.safeParse(sample);
    if (!parsed.success)
      for (const issue of parsed.error.issues)
        issues.push({ sample: i, path: issue.path.join('.'), message: issue.message });
    if (typeof sample !== 'object' || sample === null) return;
    const op = sample as Record<string, unknown>;
    for (const key of Object.keys(op)) if (!KNOWN_OPERATION_FIELDS.has(key)) unknownFields.add(key);
    for (const key of REQUIRED_OPERATION_FIELDS) if (!(key in op)) missingFields.add(key);
    for (const b of Array.isArray(op.breakdowns) ? op.breakdowns : []) {
      if (typeof b !== 'object' || b === null) continue;
      for (const key of Object.keys(b))
        if (!KNOWN_BREAKDOWN_FIELDS.has(key)) unknownFields.add(`breakdowns[].${key}`);
      for (const key of REQUIRED_BREAKDOWN_FIELDS)
        if (!(key in b)) missingFields.add(`breakdowns[].${key}`);
    }
  });
  return {
    sampled: samples.length,
    valid: issues.length === 0,
    issues: issues.slice(0, 20),
    unknownFields: [...unknownFields],
    missingFields: [...missingFields],
  };
}

export function registerDoctorCommand(program: Command): void {
  withExamples(
    program
      .command('doctor')
      .description(
        'Check auth, API reachability and whether the Dougs API still has the expected shape',
      ),
    'doctor',
    'doctor --json',
  ).action(async (_o: unknown, cmd: Command) => {
    const ctx = contextOf(cmd);
    const checks: Check[] = [
      { name: 'version', ok: true, detail: `dougs-cli ${VERSION}, Node ${process.versions.node}` },
    ];
    let drift: ReturnType<typeof schemaDrift> | null = null;
    let failure: DougsError | null = null;
    const step = async (name: string, fn: () => Promise<string>) => {
      if (failure) return checks.push({ name, ok: false, detail: 'skipped' });
      try {
        checks.push({ name, ok: true, detail: await fn() });
      } catch (e) {
        failure = toDougsError(e);
        checks.push({
          name,
          ok: false,
          detail: failure.hint ? `${failure.message} (${failure.hint})` : failure.message,
        });
      }
    };
    await step('credentials', async () => {
      const auth = await ctx.auth();
      return `profile "${auth.profileName}" from ${auth.source === 'env' ? 'DOUGS_SESSION' : `${auth.source} (${configPath(ctx.env)})`}`;
    });
    await step('session', async () => {
      const { user, companies } = await ctx.user();
      return `authenticated as user ${user.id}; ${companies.length} compan${companies.length === 1 ? 'y' : 'ies'}`;
    });
    await step('company', async () => `using company ${await ctx.companyId()}`);
    await step('operations', async () => {
      const dougs = await ctx.dougs();
      const [a, b] = await Promise.all([
        dougs.client.get(
          `/companies/${dougs.company}/operations?limit=20&offset=0&needsAttention=false&validated=false`,
        ),
        dougs.client.get(
          `/companies/${dougs.company}/operations?limit=20&offset=0&needsAttention=false&validated=true`,
        ),
      ]);
      const samples = [...z.array(z.unknown()).parse(a), ...z.array(z.unknown()).parse(b)];
      drift = schemaDrift(samples);
      if (!drift.valid)
        throw new DougsError(
          'API_SHAPE',
          `${drift.issues.length} schema issue(s) in ${samples.length} sampled operations`,
          {
            exitCode: ExitCode.network,
            hint: 'Dougs changed its API; please open an issue with: dougs doctor --json',
          },
        );
      return `${samples.length} sampled operations match the expected schema`;
    });
    await step(
      'categories',
      async () => `${(await (await ctx.dougs()).categories()).length} assignable categories`,
    );

    const ok = checks.every((c) => c.ok);
    const result = { ok, checks, schema: drift };
    ctx.out.result(result, (r) => {
      const lines = r.checks.map(
        (c) =>
          `${c.ok ? style.green('✓') : style.red('✗')} ${c.name.padEnd(11)} ${c.ok ? c.detail : style.red(c.detail)}`,
      );
      const d = r.schema as ReturnType<typeof schemaDrift> | null;
      if (d?.unknownFields.length)
        lines.push(style.yellow(`! new API fields (harmless, FYI): ${d.unknownFields.join(', ')}`));
      if (d?.missingFields.length)
        lines.push(style.yellow(`! expected fields not seen: ${d.missingFields.join(', ')}`));
      return lines.join('\n');
    });
    if (!ok) ctx.exitCode = (failure as DougsError | null)?.exitCode ?? ExitCode.network;
  });
}
